name: skripsi_kos_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  crypto: ^3.0.3
  equatable: ^2.0.5
  ficonsax: ^0.0.3
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.8.4
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_mlkit_text_recognition: ^0.11.0
  http: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.19.0

  maps_launcher: ^2.2.0
  permission_handler: ^11.0.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/animations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/app_launcher_icon.png"
  min_sdk_android: 21
